### ISSUE TITLE
HW to explore spotify data

### ISSUE THREAD

**Issue by johann-wagner** [johann-wagner/wagner-test#11]
The data is stored on [Google Drive](https://drive.google.com/drive/folders/13545cs5ZnL4xfekZgro_0LD0FkybmTqR?usp=sharing).

**Comment by johann-wagner** [comment]
**Tasks for 2023-09-10:**

- [x] Let's both create a branch to explore the Spotify data
- [ ] Create code in R and JS in respective branches
- [ ] Showcase code to each other
- [ ] Pull request and resolve any conflicts
