### ISSUE TITLE
JW to explore spotify data

### ISSUE THREAD

**Issue by johann-wagner** [johann-wagner/wagner-test#14]

**Comment by johann-wagner** [comment]
**Tasks for 2023-09-10:**

- [x] Let's both create a branch to explore the Spotify data
- [ ] Create code in R and JS in respective branches
- [ ] Showcase code to each other
- [ ] Pull request and resolve any conflicts
